[actions] fix our `comments.yml` workload
I think it broke after merging/deleting the `dev/action` branch:

    Error: Unable to resolve action `jonathanpeppers/inclusive-heat-sensor@dev/action`, unable to find version `dev/action`